version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependabot
  ignore:
  - dependency-name: io.dropwizard:*
    versions:
    - 2.+
  - dependency-name: org.glassfish.jersey.core:jersey-client
    versions:
    - "+"
  - dependency-name: io.dropwizard:dropwizard-testing
    versions:
    - 1.3.29
  - dependency-name: io.dropwizard:dropwizard-core
    versions:
    - 1.3.29
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
  - dependency-name: io.prometheus:simpleclient_servlet
    versions:
    - 0.10.0
  - dependency-name: io.prometheus:simpleclient_hotspot
    versions:
    - 0.10.0
  commit-message:
    prefix: BAU
